"""Add column demand on Battery model

Revision ID: 9d43ea98abba
Revises: f0515e402fdb
Create Date: 2026-09-20 19:44:23.382708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d43ea98abba'
down_revision: Union[str, Sequence[str], None] = 'f0515e402fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery_predictions', sa.Column('demand', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battery_predictions', 'demand')
    # ### end Alembic commands ###
